#!/bin/bash
#
# volume - dzen volume bar
#

#Customize this stuff
IF="Master"         # audio channel: Master|PCM

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -s, --status   - show current volume"
  echo "     -h, --help     - display this"
  exit 
}   
    
#Argument Parsing
case "$1" in 
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    amixer set $IF "$2%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    amixer set $IF "$2%-"
    ;;
  '-t'|'--toggle')
    amixer set $IF toggle
    ;;
  '-s'|'--status')
  	if [ `amixer get $IF | tail -1 | awk '{print$6}'` == "[on]" ]; then
		echo `amixer get $IF | tail -1 | awk '{print$4}' | sed 's/[^0-9]*//g'`
	else
		echo `amixer get $IF | tail -1 | awk '{print$4}' | sed 's/[^0-9]*//g'` Mute
	fi	
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac
